version: "3.7"
services:
  app:
    build: ./app
    volumes:
      - ./app/zomemo:/var/www/app
    env_file:
      - .env

  web:
    build: ./web
    ports:
      - "$HTTP_PORT:80"
    volumes:
      - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web/nginx/conf.d:/etc/nginx/conf.d
      - ./app/zomemo/webroot:/var/www/app/

  database:
    build: ./database
    env_file:
      - .env