version: "3.7"
services:
  app:
    build: ./app
    volumes:
      - ./app/zomemo:/var/www/app

  web:
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web/nginx/conf.d:/etc/nginx/conf.d
      - ./app/zomemo/webroot:/var/www/app/

  database:
    build: ./database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: parrot
      MYSQL_USER: parrot_user
      MYSQL_PASSWORD: parrot
      TZ: "Asia/Tokyo"